CREATE TYPE "public"."area_preferencia" AS ENUM('CVIS - Computação Visual', 'CD - Ciência de Dados', 'ICOT - Inteligência Computacional e Otimização', 'SIBW - Sistemas de Informação, Banco de Dados Web', 'IEDU - Informática & Educação', 'ES - Engenharia de Software', 'RCSD - Redes de Computadores e Sistemas Distribuídos', 'SCTR - Sistemas Ciberfísicos e de Tempo Real', 'SSEG - Segurança de Sistemas e Redes');--> statement-breakpoint
CREATE TYPE "public"."estado_civil" AS ENUM('Solteiro', 'Casado', 'Divorciado');--> statement-breakpoint
CREATE TYPE "public"."sexo" AS ENUM('Masculino', 'Feminino', 'Outro');--> statement-breakpoint
CREATE TYPE "public"."tipo_curso" AS ENUM('Doutorado', 'Mestrado');--> statement-breakpoint
CREATE TABLE "candidato_doutorado" (
	"id" serial PRIMARY KEY NOT NULL,
	"numero_inscricao" text NOT NULL,
	"status" text NOT NULL,
	"data_inscricao" timestamp NOT NULL,
	"avaliado" boolean DEFAULT false NOT NULL,
	"cpf" text NOT NULL,
	"sexo" "sexo" NOT NULL,
	"nome" text NOT NULL,
	"estado_civil" "estado_civil" NOT NULL,
	"email" text NOT NULL,
	"data_nascimento" timestamp NOT NULL,
	"raca" text NOT NULL,
	"nome_mae" text NOT NULL,
	"nome_pai" text,
	"tipo_escola_ensino_medio" text NOT NULL,
	"pais" text NOT NULL,
	"estado" text NOT NULL,
	"municipio" text NOT NULL,
	"rg" text NOT NULL,
	"orgao_expedidor" text NOT NULL,
	"estado_expedicao" text NOT NULL,
	"data_expedicao" timestamp NOT NULL,
	"titulo_eleitor" text NOT NULL,
	"secao_eleitoral" text NOT NULL,
	"zona_eleitoral" text,
	"passaporte" text,
	"cep" text NOT NULL,
	"logradouro" text NOT NULL,
	"bairro" text NOT NULL,
	"complemento" text,
	"estado_endereco" text NOT NULL,
	"municipio_endereco" text NOT NULL,
	"telefone_fixo" text,
	"telefone_celular" text NOT NULL,
	"linha_pesquisa" text NOT NULL,
	"comprovante_pag_taxa_inscricao" text NOT NULL,
	"copia_cpf" text NOT NULL,
	"copia_passaporte_ou_rne" text,
	"copia_documento_identificacao" text,
	"solicitou_isencao_taxa_inscricao" boolean DEFAULT false NOT NULL,
	"comprovacao_pesquisas" text NOT NULL,
	"possui_necessidades_especiais" boolean DEFAULT false NOT NULL,
	"vagas_negros_pardos" boolean DEFAULT false NOT NULL,
	"vagas_supranumerarias" boolean DEFAULT false NOT NULL,
	"tipo_curso" "tipo_curso" DEFAULT 'Doutorado' NOT NULL,
	"numero" text NOT NULL,
	"historico_graduacao" text NOT NULL,
	"copia_diploma_mestrado" text NOT NULL,
	"historico_mestrado" text NOT NULL,
	"nome_universidade_mestrado" text NOT NULL,
	"nome_curso_mestrado" text NOT NULL,
	"anteprojeto_tese" text NOT NULL,
	"conceito_capes_mestrado" text,
	"primeira_opcao_orientador" text NOT NULL,
	"segunda_opcao_orientador" text NOT NULL,
	"terceira_opcao_orientador" text NOT NULL,
	CONSTRAINT "candidato_doutorado_numero_inscricao_unique" UNIQUE("numero_inscricao"),
	CONSTRAINT "candidato_doutorado_cpf_unique" UNIQUE("cpf"),
	CONSTRAINT "candidato_doutorado_email_unique" UNIQUE("email"),
	CONSTRAINT "candidato_doutorado_rg_unique" UNIQUE("rg"),
	CONSTRAINT "candidato_doutorado_titulo_eleitor_unique" UNIQUE("titulo_eleitor"),
	CONSTRAINT "candidato_doutorado_passaporte_unique" UNIQUE("passaporte")
);
--> statement-breakpoint
CREATE TABLE "candidato_mestrado" (
	"id" serial PRIMARY KEY NOT NULL,
	"numero_inscricao" text NOT NULL,
	"status" text NOT NULL,
	"data_inscricao" timestamp NOT NULL,
	"avaliado" boolean DEFAULT false NOT NULL,
	"cpf" text NOT NULL,
	"sexo" "sexo" NOT NULL,
	"nome" text NOT NULL,
	"estado_civil" "estado_civil" NOT NULL,
	"email" text NOT NULL,
	"data_nascimento" timestamp NOT NULL,
	"raca" text NOT NULL,
	"nome_mae" text NOT NULL,
	"nome_pai" text,
	"tipo_escola_ensino_medio" text NOT NULL,
	"pais" text NOT NULL,
	"estado" text NOT NULL,
	"municipio" text NOT NULL,
	"rg" text NOT NULL,
	"orgao_expedidor" text NOT NULL,
	"estado_expedicao" text NOT NULL,
	"data_expedicao" timestamp NOT NULL,
	"titulo_eleitor" text NOT NULL,
	"secao_eleitoral" text NOT NULL,
	"zona_eleitoral" text,
	"passaporte" text,
	"cep" text NOT NULL,
	"logradouro" text NOT NULL,
	"bairro" text NOT NULL,
	"complemento" text,
	"estado_endereco" text NOT NULL,
	"municipio_endereco" text NOT NULL,
	"telefone_fixo" text,
	"telefone_celular" text NOT NULL,
	"linha_pesquisa" text NOT NULL,
	"comprovante_pag_taxa_inscricao" text NOT NULL,
	"copia_cpf" text NOT NULL,
	"copia_passaporte_ou_rne" text,
	"copia_documento_identificacao" text,
	"solicitou_isencao_taxa_inscricao" boolean DEFAULT false NOT NULL,
	"comprovacao_pesquisas" text NOT NULL,
	"possui_necessidades_especiais" boolean DEFAULT false NOT NULL,
	"vagas_negros_pardos" boolean DEFAULT false NOT NULL,
	"vagas_supranumerarias" boolean DEFAULT false NOT NULL,
	"tipo_curso" "tipo_curso" DEFAULT 'Mestrado' NOT NULL,
	"copia_diploma_graduacao" text NOT NULL,
	"historico_graduacao" text NOT NULL,
	"nome_universidade_graduacao" text NOT NULL,
	"nome_curso_graduacao" text NOT NULL,
	"cidade_onde_realizou_graduacao" text NOT NULL,
	"enade_do_curso_graduacao" text NOT NULL,
	"valor_do_enade_do_curso_graduacao" text NOT NULL,
	"nota_poscomp" text,
	"primeira_area_preferencia" "area_preferencia" NOT NULL,
	"segunda_area_preferencia" "area_preferencia",
	"carta_motivacao" text NOT NULL,
	CONSTRAINT "candidato_doutorado_numero_inscricao_unique" UNIQUE("numero_inscricao"),
	CONSTRAINT "candidato_doutorado_cpf_unique" UNIQUE("cpf"),
	CONSTRAINT "candidato_doutorado_email_unique" UNIQUE("email"),
	CONSTRAINT "candidato_doutorado_rg_unique" UNIQUE("rg"),
	CONSTRAINT "candidato_doutorado_titulo_eleitor_unique" UNIQUE("titulo_eleitor"),
	CONSTRAINT "candidato_doutorado_passaporte_unique" UNIQUE("passaporte")
);
